### PR TITLE
WIP: Move projects over to project.json and dotnet cli

### PR DESCRIPTION
**Pull request by kevinkuszyk**
The PR will migrate our projects over to the new dotnet cli.  I'm also considering switching the tests over to xUnit unless NUnit add support for RC2 before I finish this.

I plan to follow up with a separate PR to add support for MVC Core 1.0.

### CODE REVIEW

**Comment by CaseyBurnsSv** [comment]
Hi @kevinkuszyk -- Microsoft are phasing out **project.json**. Announced a couple of days ago.

https://wildermuth.com/2016/05/12/The-Future-of-project-json-in-ASP-NET-Core

**Comment by kevinkuszyk** [comment]
Hi @CaseyBurnsSv, it's been a while.  How are you?

Yes, I'd seen the announcements.  I want to add support for MVC Core before RTM, so we need at least two `project.json` projects.  I also like the idea of having one toolchain for the solution, rather than some on msbuild and some on dotnet cli.

Who knows at this point what the .net core tooling will look like when it reaches RTM, so I think it's ok to go with what's available today.

Would you hold off converting existing projects, and only add `project.json` where it's needed today?

**Comment by kevinkuszyk** [comment]
After giving this some more thought and reading [this conversation](https://twitter.com/jonskeet/status/733915770128900097), I think it might be good idea to hold off converting the existing projects for now.

**Comment by CaseyBurnsSv** [comment]
Hey @kevinkuszyk, yeah I am good. Was reading the announcement about project.json when I the notification for this PR.

**Pull request closed without merging**
