### PR TITLE
Aspnet core MVC 1 support

### PR DESCRIPTION
**Pull request by Gimly**
I've created a new project for the MVC Core and the Test project.

Quite a lot has changed in the MVC API, so I had to do a lot of changes. The most important are completely removing (with conditional compilation) `ViewResultAssertions` and `PartialViewResultAssertions` to recreate them in the .Net Core project. The reason for this is that they don't inherit from a `ViewResultBase` class anymore, but directly from `ActionResult`. Therefore, I couldn't use the same `Assertions` classes that were in the Shared project.

Another important change are all the Routing. I couldn't make the routing assertions work, and I was not sure how to make them work. I think that the tests don't make a lot of sense anymore, as the routing has completely changed and is much more simple to test "out of the box". I removed all the assertions for now (again with conditional compilation) this way it will be easy to add it back if needed.
An example for routing is available at [this repository](https://github.com/aspnet/Mvc/blob/6.0.0-rc1/test/Microsoft.AspNet.Mvc.FunctionalTests/RoutingTests.cs).

Other than that, everything seems to be working fine and all I did were minor changes, mostly using conditional compilation.

Tell me if there are things I should change or fix.

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
Thanks for this - I just had quick scan an everything looks good so far.  I'll give it a good look over tonight.

It looks like we have a build error:

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Error reading 'C:\projects\fluentassertions-mvc\tests\FluentAssertions.AspNetCore.Mvc.Tests\project.json' at line 24 column 27 : TODO: unknown keyword platform
  TODO: unknown keyword platform
Command exited with code 1
```

I guess it builds on your machine, and this is an issue in the AppVeyor environment?  I'll have a look at this tonight too.

And finally, is this ready for prime time?  i.e shall I ship a beta to NuGet so that you can try it out on your projects for a week or two before I ship a release build?

**Comment by Gimly** [comment]
@kevinkuszyk Yes, it does compile on my machine. I quickly checked the issue with AppVeyor, and it seems to be an issue with the version of dotnet there.

I have never used AppVeyor though, so I'm not sure if that might be the real cause or not, but would be interested by the resolution.

Well, I'm always cautious about putting things straight to production :), I'd be more confident to pass through a beta first, especially since I had to hack a few things to make it work.

**Comment by kevinkuszyk** [comment]
Ok, code looks good.  Just a couple of small issues:

1. The MVC Core sample tests are [not running](https://ci.appveyor.com/project/kevinkuszyk/fluentassertions-mvc/build/25#L473).  I think we may need to pull the sample tests out into their own project.
2. We have a couple of [broken tests](https://ci.appveyor.com/project/kevinkuszyk/fluentassertions-mvc/build/23#L466).

If you can make those changes, I'll be happy to merge.

It looks like I have some more work to get it building and packing in AppVeyor.  As soon as it does and your changes are in I'll push a beta to NuGet.

**Comment by Gimly** [comment]
The broken test is weird, it might be that I broke something on other versions of the FW... I'll look into that.

One really annoying thing is that it's difficult to run the tests with the different versions of the framework. Did you have something to help with that?

For the sample tests it might be that I missed to add the test runner to the project. I'll check if that fixes the issue, otherwise I'll probably have to put them in their own projects, which is kind of annoying.

Do you think those sample projects are really valueable? Maybe it would be more interesting to put them in their own repositories, this way they don't pollute the main source with things that are not necessarly related?

**Comment by Gimly** [comment]
Now everything should be working. You just have to fix the line for the sample tests to `dotnet test samples\FluentAssertions.AspNetCore.Mvc.Sample.Tests` instead of what you have now in the AppVeyor script and all tests should be passing.

**Comment by kevinkuszyk** [comment]
Thanks @Gimly - we have a green build now.  I just need to add some metadata to the `project.json` and then it's ready for a beta on NuGet.  Hopefully I'll get that done tonight.

**Comment by kevinkuszyk** [comment]
Just released I missed a couple of questions.

> One really annoying thing is that it's difficult to run the tests with the different versions of the framework. Did you have something to help with that?

I just run them in ReSharper - it seems to discover them all.

> Do you think those sample projects are really valueable? Maybe it would be more interesting to put them in their own repositories, this way they don't pollute the main source with things that are not necessarly related?

For me they have a couple of purposes:

1. To verify everything is working in a more real world environment.
2. To provide a place to write example tests which can be used in the documentation.  And yes - I'm aware that it is very much lacking.

**Comment by Gimly** [comment]
Weird, ReSharper on my machine only runs the "standard" .Net tests, and not the .Net Core tests, and the test launcher from VS 2015 only runs the .Net Core tests (except the one in the sample because reasons).

I didn't question the use of the sample apps, but more if they make sense to be in the same solution as the rest of the code. It's just that it makes the things a bit messy. I've seen a lot of open source projects that instead put them outside or even in their own repository. But in the end it's also OK like that, just makes a lot of projects.

Glad that I could help :)
I'll probably help again, depending on my needs and/or if I have time to offer.

Cheers.

**Comment by kevinkuszyk** [comment]
> Weird, ReSharper on my machine only runs the "standard" .Net tests, and not the .Net Core tests, and the test launcher from VS 2015 only runs the .Net Core tests (except the one in the sample because reasons).

Apologies - I misunderstood.  Yes, I think support for .net core tests is coming in the next version of ReSharper.

`FluentAssertions.AspNetCore.Mvc` `0.7.0-beta1` is up on NuGet now.   Can you test it for a couple of weeks, and if there's no issues I'll drop the beta tag.

**Comment by kevinkuszyk** [comment]
@Gimly how's the testing on `0.7.0-beta1` going?  If it's looking good I'll drop the beta tag and push a new version.

**Pull request merged**
